import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getTableColumns, getTableName } from "drizzle-orm";
import { getTableConfig, type PgTable } from "drizzle-orm/pg-core";
import { relationalTables } from "./schema.js";
import { TABLE_NAMES } from "./table-names.js";

interface GeneratedColumn {
  readonly ts: string;
  readonly sql: string;
  readonly sqlType: string;
  readonly dataType: string;
  readonly notNull: boolean;
  readonly hasDefault: boolean;
  readonly primary: boolean;
  readonly unique: boolean;
  readonly tsType: string;
}

interface GeneratedForeignKey {
  readonly columns: readonly string[];
  readonly foreignTable: string;
  readonly foreignColumns: readonly string[];
  readonly onDelete: string;
}

interface GeneratedIndex {
  readonly name: string;
  readonly unique: boolean;
  readonly columns: readonly string[];
}

interface GeneratedTable {
  readonly name: string;
  readonly columns: readonly GeneratedColumn[];
  readonly primaryKey: readonly string[];
  readonly unique: readonly (readonly string[])[];
  readonly foreignKeys: readonly GeneratedForeignKey[];
  readonly indexes: readonly GeneratedIndex[];
  readonly checks: readonly string[];
}

function tsTypeForColumn(table: string, column: GeneratedColumn): string {
  if (table === "blockers" && column.ts === "status") {
    return "BlockerStatus";
  }
  if (table === "standups" && column.ts === "rawBlockers") {
    return "RawBlocker[]";
  }
  switch (column.dataType) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "date":
      return "Date";
    case "json":
      return "unknown";
    default:
      return "unknown";
  }
}

function namedColumns(columns: readonly unknown[]): string[] {
  const names: string[] = [];
  for (const column of columns) {
    if (typeof column !== "object" || column === null || !("name" in column)) {
      continue;
    }
    const name = column.name;
    if (typeof name === "string" && name.length > 0) {
      names.push(name);
    }
  }
  return names;
}

function inspectTable(table: PgTable): GeneratedTable {
  const config = getTableConfig(table);
  const columnMap = getTableColumns(table);
  const columns: GeneratedColumn[] = Object.entries(columnMap).map(([ts, column]) => {
    const base = {
      ts,
      sql: column.name,
      sqlType: column.getSQLType(),
      dataType: column.dataType,
      notNull: column.notNull,
      hasDefault: column.hasDefault,
      primary: column.primary,
      unique: column.isUnique,
    };
    return { ...base, tsType: tsTypeForColumn(config.name, { ...base, tsType: "unknown" }) };
  });

  const pkFromConstraint = config.primaryKeys.flatMap((key) => namedColumns(key.columns));
  const pkFromColumns = columns.filter((column) => column.primary).map((column) => column.sql);
  const primaryKey = [...new Set([...pkFromConstraint, ...pkFromColumns])];

  const uniqueFromColumns = columns.filter((column) => column.unique).map((column) => [column.sql]);
  const uniqueFromIndexes = config.indexes
    .filter((entry) => entry.config.unique)
    .map((entry) => namedColumns(entry.config.columns));
  const uniqueFromConstraints = config.uniqueConstraints.map((entry) =>
    namedColumns(entry.columns),
  );
  const unique = [...uniqueFromColumns, ...uniqueFromIndexes, ...uniqueFromConstraints];

  const foreignKeys: GeneratedForeignKey[] = config.foreignKeys.map((fk) => {
    const reference = fk.reference();
    return {
      columns: namedColumns(reference.columns),
      foreignTable: getTableName(reference.foreignTable),
      foreignColumns: namedColumns(reference.foreignColumns),
      onDelete: fk.onDelete ?? "no action",
    };
  });

  const indexes: GeneratedIndex[] = config.indexes.map((entry) => ({
    name: entry.config.name ?? "",
    unique: entry.config.unique,
    columns: namedColumns(entry.config.columns),
  }));

  return {
    name: config.name,
    columns,
    primaryKey,
    unique,
    foreignKeys,
    indexes,
    checks: config.checks.map((entry) => entry.name),
  };
}

function emitCatalog(tables: readonly GeneratedTable[]): string {
  const body = JSON.stringify({ tables }, null, 2);
  return `/**
 * AUTO-GENERATED by src/db/generate-types.ts. Do not edit.
 * Source of truth: src/db/schema.ts
 */
export const generatedCatalog = ${body} as const;
`;
}

function emitRows(tables: readonly GeneratedTable[]): string {
  const interfaces = tables
    .map((table) => {
      const ident = rowInterfaceName(table.name);
      const fields = table.columns
        .map((column) => `  readonly ${column.ts}: ${column.tsType};`)
        .join("\n");
      return `export interface ${ident} {\n${fields}\n}`;
    })
    .join("\n\n");

  return `/**
 * AUTO-GENERATED persistence row shapes from src/db/schema.ts.
 * Wire types (ISO strings) live in @pulseboard/types.
 */
import type { BlockerStatus, RawBlocker } from "@pulseboard/types";

${interfaces}
`;
}

function rowInterfaceName(table: string): string {
  switch (table) {
    case "users":
      return "GeneratedUserRow";
    case "workspaces":
      return "GeneratedWorkspaceRow";
    case "workspace_members":
      return "GeneratedWorkspaceMemberRow";
    case "standups":
      return "GeneratedStandupRow";
    case "blockers":
      return "GeneratedBlockerRow";
    case "weekly_digests":
      return "GeneratedWeeklyDigestRow";
    default:
      throw new Error(`unknown table ${table}`);
  }
}

function main(): void {
  const tables = relationalTables.map((table) => inspectTable(table));
  const names = tables.map((table) => table.name);
  if (names.join(",") !== TABLE_NAMES.join(",")) {
    throw new Error(
      `table order/name drift: schema has [${names.join(", ")}] expected [${TABLE_NAMES.join(", ")}]`,
    );
  }

  const here = dirname(fileURLToPath(import.meta.url));
  const outDir = join(here, "generated");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "catalog.ts"), emitCatalog(tables));
  writeFileSync(join(outDir, "rows.ts"), emitRows(tables));
  process.stdout.write(`generated ${tables.length} table catalogs\n`);
}

main();
